### PR TITLE
Add cpuinfo dump using cpuid

### PR DESCRIPTION
**Pull request by Saruta**
This feature can be very useful for several things:
- First, it's almost mandatory if we want to implement further funny kernel features (64 bits, smp ...)
- It can also be useful if we want to run the kernel on old hardware.
- It allows ```cat /proc/cpuinfo``` for debug/info purpose.

### CODE REVIEW

**Comment by PoisonNinja** [comment]
What happened?

**Comment by Saruta** [comment]
My tree wasn't very clean, so I will reopen a better PR.

**Comment by PoisonNinja** [comment]
Ah ok. Do you want direct write access to my source tree?

**Comment by Saruta** [comment]
It can be useful for small patches yes, but I prefer use PR or classical patches for real features as we can discuss of it before merging it to the tree.

**Comment by PoisonNinja** [comment]
ok

**Pull request closed without merging**
