### PR TITLE
Build libstar

### PR DESCRIPTION
**Pull request by PoisonNinja**
Build libstar, which is a custom library for making and decompressing tar files. A library (libstar.a) is available. Simply link against it with -lstar. Also, libstar.h is in the include folder under star/.

NOT READY YET!

### CODE REVIEW

**Comment by PoisonNinja** [comment]
libarchive already exists

**Comment by PoisonNinja** [comment]
@Saruta what do you think?

**Comment by Saruta** [comment]
It could be great to have libarchive, yes.

**Comment by PoisonNinja** [comment]
nvm libarchive doesn't work.

**Comment by PoisonNinja** [comment]
So, if you want to use libtar, just copy the two files into upkg. Userspace programs such as tar can directly the copy of libtar in the userspace/lib folder.

**Pull request merged**
